
export const DILER_JINNY = 'DILER_JINNY',
  PLAYER_ALADDIN = 'PLAYER_ALADDIN',
  PLAYER_YAGO = 'PLAYER_YAGO',
  PLAYER_CARPET = 'PLAYER_CARPET',
  PLAYER_WALLE = 'PLAYER_WALLE',
  PLAYER_JASMINE = 'PLAYER_JASMINE',
  PLAYER_SULTAN = 'PLAYER_SULTAN',
  PLAYER_TIGER = 'PLAYER_TIGER',
  PLAYER_EVE = 'PLAYER_EVE',
  PLAYER_ABU = 'PLAYER_ABU'


export type AvailablePlayerNames = 'PLAYER_ALADDIN' | 'PLAYER_YAGO' | 'PLAYER_ABU'
  | 'PLAYER_WALLE' | 'PLAYER_TIGER' | 'PLAYER_EVE' | 'PLAYER_CARPET'
  | 'PLAYER_JASMINE' | 'PLAYER_SULTAN'
